/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PodmienkyAmbasadorskehoProgramuRouteImport } from './routes/podmienky-ambasadorskeho-programu'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PodmienkyAmbasadorskehoProgramuRoute =
  PodmienkyAmbasadorskehoProgramuRouteImport.update({
    id: '/podmienky-ambasadorskeho-programu',
    path: '/podmienky-ambasadorskeho-programu',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/podmienky-ambasadorskeho-programu': typeof PodmienkyAmbasadorskehoProgramuRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/podmienky-ambasadorskeho-programu': typeof PodmienkyAmbasadorskehoProgramuRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/podmienky-ambasadorskeho-programu': typeof PodmienkyAmbasadorskehoProgramuRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/podmienky-ambasadorskeho-programu'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/podmienky-ambasadorskeho-programu'
  id: '__root__' | '/' | '/podmienky-ambasadorskeho-programu'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PodmienkyAmbasadorskehoProgramuRoute: typeof PodmienkyAmbasadorskehoProgramuRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podmienky-ambasadorskeho-programu': {
      id: '/podmienky-ambasadorskeho-programu'
      path: '/podmienky-ambasadorskeho-programu'
      fullPath: '/podmienky-ambasadorskeho-programu'
      preLoaderRoute: typeof PodmienkyAmbasadorskehoProgramuRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PodmienkyAmbasadorskehoProgramuRoute: PodmienkyAmbasadorskehoProgramuRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
